---
title: "About"
format: html
editor: visual
---

This project was developed by **"Hunger Games, Catching Meyer"** For [STA 199: Introduction to Data Science](https://sta199-s23-2.github.io/) at Duke University. The team is comprised of the following team members.

-   Janet Jiang: A sophomore from Hsinchu, Taiwan. She is studying Computer Science and Economics and hopes to either work as a software engineer or pursue a post-doctoral degree in CS.
-   Kyra Chen: A freshman intending to major in biology and potentially minoring in computational biology and global health.
-   Will Adams: A junior creating a Program II titled, The Global Sports World: Money, Power, & Culture. Hope to work in the sports, media, and entertainment investment world, pushing the boundaries of human immersive experiences.
-   Maile Lehrer: A senior studying Cultural Anthropology and Political Science. Post-graduation plans include living abroad and working for a (hopefully) living wage while attempting to distance themself from the ever-pervasive grind culture. 

This project aims to determine what factors impact Alexandra Trusova's jump performance in ice skating competitions. In our project, we sourced data from the International Skating Union's databases and individual countrys' skating association websites and conducted hypothesis tests to evaluate whether changes in altitude, competition distance from Moscow, and the difficulty of the jump respectively impacted Trusova's jump performance, creating predictive models and visualizations to support our results. We conclude that no singular factor has a significant impact on Trusova's jump performance. Although our conclusions cannot be generalized to the sport of figure skating as a whole until it can be supported by data gathered from the careers of other skaters, they do indicate the need for additional competition data and more skater-specific sensitive information, like body weight, injury status, and mental health state, to be collected for further research.
